# Generated by Django 4.2.7 on 2024-06-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='歌手名称', max_length=50)),
                ('photo', models.CharField(help_text='头像文件名称', max_length=50)),
                ('desc', models.CharField(help_text='描述', max_length=1000)),
            ],
        ),
    ]
