# Generated by Django 4.2.7 on 2024-06-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='歌手名称', max_length=50)),
                ('photo', models.CharField(help_text='图片文件名称', max_length=50)),
                ('desc', models.CharField(help_text='描述', max_length=1000)),
                ('singer', models.ForeignKey(help_text='歌手ID外键', on_delete=django.db.models.deletion.CASCADE, to='audio_manage.singer')),
            ],
        ),
    ]
