# Generated by Django 4.2.7 on 2024-06-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manage', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(help_text='歌手ID外键', null=True, on_delete=django.db.models.deletion.CASCADE, to='audio_manage.singer'),
        ),
    ]
