# Generated by Django 4.2.7 on 2024-06-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
        ('audio_manage', '0003_alter_album_singer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分组名称', max_length=50)),
                ('desc', models.CharField(help_text='分组描述', max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('private', models.BooleanField(default=True, help_text='分组是否私密')),
                ('create_user', models.ForeignKey(help_text='创建用户ID', on_delete=django.db.models.deletion.CASCADE, to='user_manage.usermodel')),
            ],
        ),
    ]
