# Generated by Django 4.2.7 on 2024-06-19 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
        ('audio_manage', '0004_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='歌手名称', max_length=50)),
                ('file_name', models.CharField(help_text='图片文件名称', max_length=50)),
                ('upload_time', models.DateTimeField(auto_now=True, help_text='上传时间')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.CharField(help_text='主题图片文件名称', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.CharField(help_text='图片文件名称', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='photo',
            field=models.CharField(help_text='头像文件名称', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AudioGroupMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(help_text='音频ID外键', on_delete=django.db.models.deletion.CASCADE, to='audio_manage.audio')),
                ('group', models.ForeignKey(help_text='分组ID外键', on_delete=django.db.models.deletion.CASCADE, to='audio_manage.group')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.ForeignKey(help_text='专辑ID外键', on_delete=django.db.models.deletion.CASCADE, to='audio_manage.album'),
        ),
        migrations.AddField(
            model_name='audio',
            name='singer',
            field=models.ForeignKey(help_text='歌手ID外键', on_delete=django.db.models.deletion.CASCADE, to='audio_manage.singer'),
        ),
        migrations.AddField(
            model_name='audio',
            name='upload_user',
            field=models.ForeignKey(help_text='上传用户ID外键', on_delete=django.db.models.deletion.CASCADE, to='user_manage.usermodel'),
        ),
    ]
