# Generated by Django 4.2.7 on 2024-06-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manage', '0005_audio_group_photo_alter_album_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='upload_user',
        ),
    ]
