# Generated by Django 4.2.7 on 2024-05-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(help_text='账号', max_length=255, unique=True)),
                ('name', models.CharField(help_text='昵称', max_length=255)),
                ('password', models.CharField(help_text='密码', max_length=255)),
                ('is_admin', models.BooleanField(help_text='是否为管理员')),
            ],
        ),
    ]
