# Generated by Django 4.2.7 on 2024-06-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.CharField(help_text='头像名称', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='是否为管理员'),
        ),
    ]
