# Generated by Django 4.2.7 on 2023-12-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(help_text='标签ID', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='标签名称', max_length=10)),
                ('description', models.TextField(help_text='标签描述')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.AutoField(help_text='视频信息ID', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='视频名称', max_length=20)),
                ('type', models.TextField(choices=[('Film', '电影'), ('TvDrama', '电视剧'), ('Otheres', '其它')], help_text='视频类型')),
                ('labels', models.TextField(help_text='标签ID列表')),
                ('episodes', models.IntegerField(help_text='总集数')),
                ('file_path', models.TextField(help_text='文件路径')),
            ],
        ),
    ]
