# Generated by Django 4.2.7 on 2023-12-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='description',
            new_name='desc',
        ),
    ]
